# Generated by cucumber-sinatra. (2014-10-04 12:11:12 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/game.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = game

class gameWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  gameWorld.new
end
